# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 6  # 类别数目
depth_multiple: 0.5
width_multiple: 0.75

train:
  batch_size: 8  # 批大小
  epochs: 100  # 训练轮数
  learning_rate: 0.001  # 初始学习率
  weight_decay: 0.0005  # 权重衰减（L2惩罚）
  momentum: 0.937  # SGD动量
  warmup_epochs: 3.0  # 预热期轮数
  optimizer: Adam

augmentation:
  hsv_h: 0.02  # 提高以增加变化
  hsv_s: 0.8  # 提高以增加变化
  hsv_v: 0.5  # 提高以增加变化
  degrees: 5.0  # 添加小的旋转
  translate: 0.1
  scale: 0.5
  shear: 0.1  # 添加剪切变换
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  bgr: 0.0
  mosaic: 1.0
  mixup: 0.0
  copy_paste: 0.0

inference:
  confidence_threshold: 0.2  # 置信度阈值
  nms_iou_threshold: 0.5  # NMS的IoU阈值
  max_det: 200

loss:
  box_loss_gain: 0.2  # 提高以更专注于框的精度
  cls_loss_gain: 0.5
  dfl_loss_gain: 0.3
  iou_loss: CIOU  # IoU损失函数为CIOU

scales:  # 模型复合缩放常数，例如'model=yolov8n.yaml'将调用yolov8.yaml并使用'scale'为'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]  # YOLOv8n 摘要: 225 层, 3157200 参数, 3157184 梯度, 8.9 GFLOPs
  s: [0.33, 0.50, 1024]  # YOLOv8s 摘要: 225 层, 11166560 参数, 11166544 梯度, 28.8 GFLOPs
  m: [0.67, 0.75, 768]  # YOLOv8m 摘要: 295 层, 25902640 参数, 25902624 梯度, 79.3 GFLOPs
  l: [1.00, 1.00, 512]  # YOLOv8l 摘要: 365 层, 43691520 参数, 43691504 梯度, 165.7 GFLOPs
  x: [1.00, 1.25, 512]  # YOLOv8x 摘要: 365 层, 68229648 参数, 68229632 梯度, 258.5 GFLOPs

# YOLOv8.0n 主干网络
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n 检测头部
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]]  # 连接主干网络的P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]]  # 连接主干网络的P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # 连接检测头部的P4
  - [-1, 3, C2f, [512]]  # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # 连接检测头部的P5
  - [-1, 3, C2f, [1024]]  # 21 (P5/32-large)

  - [[15, 18, 21], 1, Detect, [nc]]  # 检测层（使用P3, P4, P5）
